language: android

jdk:
  - oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # default is 2 minutes and sometimes is not enough
    - ANDROID_ABI=armeabi-v7a # x86 is not supported yet :(
    - BUILD_TOOLS_VERSION=23.0.2
    - COMPILE_SDK_VERSION=22
  matrix:
    - ANDROID_TARGET_VERSION=15
    - ANDROID_TARGET_VERSION=16
    - ANDROID_TARGET_VERSION=19
    - ANDROID_TARGET_VERSION=21
    - ANDROID_TARGET_VERSION=22

android:
  components:
    - platform-tools
    - tools

    - build-tools-$BUILD_TOOLS_VERSION

    - android-$COMPILE_SDK_VERSION
    - android-23 # for java7test

    - extra-android-m2repository

    - sys-img-$ANDROID_ABI-android-$ANDROID_TARGET_VERSION

# Emulator Management: Create, Start and Wait
before_script:
  # reply 'no' to 'Create custom emulator configuration?'
  - echo no | android create avd --force --name test --target "android-$ANDROID_TARGET_VERSION" --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  # unlock screen:
  - adb shell input keyevent 82

script:
  - ./gradlew connectedAndroidTest
